use `allteam`;

SET FOREIGN_KEY_CHECKS = 0;

LOAD DATA LOCAL INFILE 'nurse.unl' 
INTO TABLE nurse
FIELDS TERMINATED BY '|' ;

LOAD DATA LOCAL INFILE 'NursePerson.unl' 
INTO TABLE person
FIELDS TERMINATED BY '|';

SET FOREIGN_KEY_CHECKS = 1;